[[catalog]]
label = "RSoXS Demo"
url = "http://tiled-demo.blueskyproject.io"
catalog_keys = ["rsoxs", "raw"]
catalog_model = "blueskycatalog"

[[catalog]]
label = "BMM Demo"
url = "http://tiled-demo.blueskyproject.io"
catalog_keys = ["bmm","raw"]
catalog_model = "blueskycatalog"