[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "nbs-viewer"
description = "A simple viewer application for data stored in a Blueksy-Tiled database."
dynamic = ["version"]
authors = [{ name = "Charles Titus", email = "ctitus@bnl.gov" }]
readme = "README.md"
keywords = ["tiled", "viewer"]
dependencies = [
"numpy",
"qtpy",
"matplotlib",
"tiled",
"bluesky-widgets >= 0.0.15",
"pyzmq",
"bluesky-kafka",
"nslsii",
"databroker[client,server,back-compat]",
"bluesky-tiled-plugins",
"asteval",
"tomli >= 2.0.0; python_version < '3.11'", "pytest>=9.0.3,<10",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research"
]

[project.urls]
Homepage = "https://github.com/xraygui/nbs-viewer"
Issues = "https://github.com/xraygui/nbs-viewer/issues"

[project.scripts]
nbs-viewer = "nbs_viewer.viewer:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["nbs_viewer"]

[project.entry-points."nbs_viewer.catalog_models"]
blueskycatalog = "nbs_viewer.models.catalog.bluesky:BlueskyCatalog"
nbscatalog = "nbs_viewer.models.catalog.bluesky:NBSCatalog"

[project.entry-points."nbs_viewer.plot_displays"]
matplotlib = "nbs_viewer.views.display.plotDisplay:PlotDisplay"
image_grid = "nbs_viewer.views.display.plotDisplay:ImageGridDisplay"

[project.entry-points."nbs_gui.tabs"]
nbs-viewer-kafka = "nbs_viewer.widgets.kafkaViewerTab:KafkaViewerTab"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
nbs-viewer = { path = ".", editable = true }

[tool.pixi.tasks]
nbs-viewer = "nbs-viewer"

[tool.pixi.dependencies]
nslsii = ">=0.11.2,<0.12"
numpy = ">=2.2.6,<3"
qtpy = ">=2.4.3,<3"
matplotlib = ">=3.10.6,<4"
tiled = ">=0.2.9,<0.3"
bluesky-widgets = ">=0.0.17,<0.0.18"
bluesky-live = ">=0.0.8,<0.0.9"
qt6-wayland = ">=6.9.2,<7"
pyside6 = ">=6.9.2,<7"
pyqtgraph = ">=0.13.7,<0.14"
pyzmq = ">=27.1.0,<28"
bluesky-tiled-plugins = ">=2.0.3,<3"
databroker = ">=2.0.0,<3"
asteval = ">=1.0.6,<2"
